# file: .github/workflows/test-workflow.yml
name: test-hw
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # sayhello – произвольно выбранное имя задания
  # их может быть больше одного
  sayhello:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: 
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v2
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - run: make say-hello
